@startuml
skinparam classAttributeIconSize 0
skinparam monochrome true
skinparam shadowing false

title Class Diagram - Multi-Matical Supporter system

class MainMenu {
  - learning and computing support program
  + start_app()
}

class calculator {
  + {static} open a basic calculus for the user\n to make many caculations.
}

class converter {
  + {static} open a converter that the user\n can easily convert between coefficients
}

class Diagram {
  + {static} open a simulation of a diagram to show\n the value of a function.
}

class Diagram_3D {
  + {static} help the students to image the coordinary3D\n system in 3D when they draw vector or shpere\n function
}

class color_tools {
  + {static} help the student to mix the color and get the HEX and RGB code for coding and creation
}

class snake_game {
  + {static} a game help student to entertain after learning\n which is not cause addicted for student
}

' Quan hệ phụ thuộc (Dependency) từ Menu chính gọi đến các module chức năng
MainMenu ..> calculator : <<use>>
MainMenu ..> converter : <<use>>
MainMenu ..> Diagram : <<use>>
MainMenu ..> Diagram_3D : <<use>>
MainMenu ..> snake_game : <<use>>
MainMenu ..> color_tools : <<use>>

note bottom of MainMenu
  The main Tkinter interface acts
  as a navigation tool, guiding
  users to the corresponding
  functions via buttons.
end note

note "These classes represent independent functional modules." as N1
calculator .. N1
converter .. N1
Diagram .. N1
Diagram_3D .. N1
snake_game .. N1
color_tools .. N1

@enduml
